name: Tests
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
concurrency:
  group: tests-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    name: pytest (${{ matrix.python-version }})
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.13.13"]
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Configure fast apt mirror
        uses: vegardit/fast-apt-mirror.sh@v1
      - name: Install system dependencies
        uses: gerlero/apt-install@v1
        with:
          packages: build-essential libevdev-dev libleptonica-dev python3-evdev libtesseract-dev pkg-config tesseract-ocr
          install-recommends: false
      - name: "Set up Python"
        uses: actions/setup-python@v6
        with:
          python-version-file: "pyproject.toml"
      - name: Install uv
        uses: astral-sh/setup-uv@v8.1.0
        with:
          enable-cache: true
          activate-environment: true
          ignore-nothing-to-cache: true
          ignore-empty-workdir: true
          cache-dependency-glob: |
            uv.lock
            pyproject.toml
      - name: Install dependencies
        run: uv sync --all-extras --frozen
      - name: Run pytest
        run: uv run pytest --tb=short -q
